[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
qstring = "*"
derive_more = "*"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
actix-cors = "0.6"